---
title: Bird genetic diversity
author: Alex Reinhart
date: July 10, 2019
description: Evolutionary theory suggests that species spread over a wider geographic range should have greater genetic diversity. Does this hold true in birds? An observational study of 387 bird species.
categories:
  - linear regression
  - hierarchical model
---

## Motivation

Ecologists and evolutionary biologists have long investigated links between
diversity and geography. For example, as the area of a habitat increases, the
[number of different species found within it
increases](https://en.wikipedia.org/wiki/Species%E2%80%93area_relationship)—a
seemingly obvious finding, but the exact shape of the relationship has been
found to relate to the rates of immigration and extinction in the habitat,
predator-prey behaviors, and so on.

A similar relationship would seem likely to exist within a species. A species
that lives over a small area might have low genetic diversity, because
individuals frequently interbreed and there is little opportunity for some
individuals to evolve separately from others. A species that lives over a wide
area might have high genetic diversity, both because the varied habitat in which
it lives means different individuals experience different natural selection
pressures, and because individuals far apart may never be able to interbreed.

The exact nature of this relationship could be used to test hypotheses about
evolution and natural selection. This dataset comes from a paper that explored
the relationship in birds, which have widely varying geographic ranges and hence
could be a good group to work with.

## Data

This data includes 387 bird species, along with two measures of their genetic
diversity, a measure of the size of their breeding range, their body mass, and
whether they are migratory or resident birds. The breeding ranges vary in size
from a just few islands in the Seychelles, for the Seychelles warbler
(*Acrocephalus sechellensis*), to enormous ranges of the Southern Ocean for the
grey-headed albatross (*Thalassarche chrysostoma*).

| Variable | Description |
|----|-------------|
| Species |	Bird species name |
| Family |	Family of birds to which this species belongs |
| Heterozygosity |	A measure of genetic richness. Birds (and most animals) have two copies of each chromosome; expected heterozygosity is the probability that for a randomly selected gene, these two copies will be different versions (alleles) of the gene. |
| Allelic richness | 	The average number of different alleles (versions of a gene) for each gene. |
| Breeding range size |	Size of the spatial range over which this bird breeds, in units of 10,000 square km |
| Body mass |	Average body mass of the species (grams) |
| Latitude |	Mid-point latitude of the species breeding range. (All latitudes are positive, even those in the southern hemisphere.) |
| Migratory status |	Is this species migratory or does it stay resident in one area? |
| References |	References for the data for this species  |

: [verlander-pitches-2022.csv](../data/verlander-pitches-2022.csv)

## Questions

1. Body size and latitude are thought to be related to genetic diversity for
   reasons unrelated to breeding range size. Regress heterozygosity against
   breeding range size, body mass, and latitude. Examine the shape of the
   relationship, which is thought not to be linear and suspected to have an
   asymptote. Does the relationship depend on whether the species are migratory?
   Compare this to the shape you find using allelic richness instead of
   heterozygosity as the outcome.
2. Species in this dataset are grouped into families; by definitions, species
   within a family are more similar than species in two different families. This
   may have effects on the assumptions of the regression. What assumptions may
   be violated, and what effect would this have on your results? (Note that the
   original paper accounted for this effect by taking into account the species’
   phylogenetic trees.)
3. Fit a hierarchical model to account for this effect, using family to define
   the hierarchy. How do your results change?


## References

Fan H, Zhang Q, Rao J, Cao J, Lu X (2019) Genetic diversity-area relationships
across bird species. *The American Naturalist*, volume 194, number 5.
<https://doi.org/10.1086/705346>

Fan H, Zhang Q, Rao J, Cao J, Lu X (2019) Data from: Genetic diversity-area
relationships across bird species. *Dryad Digital Repository*.
<https://doi.org/10.5061/dryad.9p380m9>
