project:
  type: website
  resources:
    - "data/*.csv"
    - "data/*.txt"
    - CNAME

website:
  title: "SCORE Sports Data Repository"
  page-footer: "Maintained by [Ron Yurko](https://www.stat.cmu.edu/~ryurko/)"
  cookie-consent: true
  google-analytics: "G-TR6GTHPX8L"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - by-statsds-topic.qmd
      - submit-data.qmd
      - data-sources.qmd
      - href: https://modules.scorenetwork.org/
        text: Module Repository
      - href: https://scorenetwork.org/index.html
        text: SCORE Network
    right:
      - icon: twitter
        href: https://twitter.com/scorenetworkorg
      - icon: linkedin
        href: https://www.linkedin.com/company/scorenetworkorg/
  sidebar:
    contents: auto
    collapse-level: 1
  repo-url: https://github.com/SCOREnetworkorg/sports-data-repository
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - cosmo
      - score.scss
    toc: true

execute:
  freeze: auto
