---
title: Handball - Individual Player Statistics for the 2022-2023 Season
author: Abigail Smith
date: June 7, 2024
description: Comparing offensive statistics to penalties for individual players in the Handball-Bundesliga for the 2022-23 season.
categories:
  -  Confidence interval for a mean
  -  Prediction interval for regression
  -  Linear regression
  -  Multiple regression
  -  Correlation
  
editor: 
  markdown: 
    wrap: 72
---

## Motivation

[Handball](https://en.wikipedia.org/wiki/Handball){target="_blank"} is a popular sport in many European countries such as Germany
where it is said to have originated. The [Bundesliga](https://en.wikipedia.org/wiki/Bundesliga){target="_blank"}, for example, is a
German men's professional handball league. Handball is typically played
indoors on a rectangular court (20m x 40m). There are two goals (3m x
2m) on opposite sides of the court, the goal for each team is to score a
goal by getting the ball in the other team's goal. The challenge to this
is that there is a semicircle with a radius of 6m surrounding the goal
which players other than the goal keeper are not allowed in, making it
challenging to score. Players run back and forth down the court passing
the ball to each other and trying to score. 

There are seven positions total in handball: the goalkeeper who defends the team's goal, left and
rights backs are positioned on the left and right side of their half of
the court to provide further defense, the center can move up and down
the court and is usually the one trying to score, left and right wings
can also move up and down the court, serving as offense when the team
pushes for attack and defense when the opposing team tries to score,
lastly, the pivot is considered strictly an offensive player as they are
usually position in the opposing side of the court, they often work
closely with the center. The Bundesliga regular season length is 34
games, with playoffs the maximum number of games a team could play is
41. Players do not play every game in the season and subbing is common,
generally speaking playing time goes to players with experience. This can create a bit of a disparity in which players with less
playing time will not necessarily have statistics that accurately
display their skills due to the smaller sample size.

Handball is considered a contact sport which means aggressive strategies
are often used in games. Aggressiveness can be measured in the penalty
statistics as players who tend to get more penalties are usually more
considered more aggressive players overall. Their success can be
measured with the [handball performance index (HPI)](https://www.liquimoly-hbl.de/en/s/handball-performance-index/2021-22/handball-performance-index--data-based--transparent--fair/){target="_blank"}. According to Bundesliga, HPI "measures and illustrates a player's performance during a game, a month or an entire season with the help of a concrete numerical value". Players' HPIs are calculated by plus and minus points based on their actions during games. This data set could provide insight on if players or teams that are more aggressive as measured by penalties are more successful than those
who are more passive. 

## Data

The data set has 309 players from 18 different clubs, with 7 variables, 4
of which are statistics. Each row in the data set is a player in the
Handball-Bundesliga during the 2022-23 season. The statistics are
cumulative for the entirety of the season. The data set only contains players who played in 10 games or more.

| Variable          | Description                                                                                                                                                                                                                   |
|--------------------|----------------------------------------------------|
| `NAME` | The name of the player. |
| `CLUB`            | The club the player is on. There are 18 in the Bundesliga.                                                                                                                                                                    |
| `POSITION`        | The position of the player. There are 7 positions in handball: goalkeeper, fullbacks (left and right), center backcourt, wingers (left and right), and pivot.                                                                 |
| `P`               | The number of games played in the 2022-23 season.                                                                                                                                                                           |
| `total_offense`   | The total offensive plays made by the player in the season. Calculated by adding the 6 offensive focused statistics from the original dataset.                                                                                |
| `total_penalties` | The total penalties the player had in the season. Calculated by adding the 5 penalty related statistics from the original dataset.|                                                             
| `HPI`             | Handball performance index, complex formulaic calculation equivalent to how well the player performed in the season. Players with HPIs in the 70s are considered good, while players in the 60s are considered not as strong. [https://www.liquimoly-hbl.de/en/s/handball-performance-index/2021-22/handball-performance-index--data-based--transparent--fair/](https://www.liquimoly-hbl.de/en/s/handball-performance-index/2021-22/handball-performance-index--data-based--transparent--fair/){target="_blank"}|

: [handball_bundesliga_23.csv](../data/handball_bundesliga_23.csv){target="_blank"}

## Questions

1.  Treating this season as a sample, find a 98% confidence interval for the mean HPI of Bundesliga handball players. 

2.  Fit a regression model to predict HPI using total_penalties. 

3.  Find and interpret a 98% confidence interval for the mean HPI
    of all players with 30 total_penalties. 

4.  Find and interpret a 98% prediction interval for the HPI of a
    player with 30 total_penalties. 

5.  Perform an ANOVA test to assess the overall fit of `HPI` =
    `total_offense` + `total_penalties`. Provide an interpretation of
    the results. 
    
6.  Find the correlation of total_penalties and total_offense. 

7.  Test the significance of the correlation between the `total_offense`
    and the `total_penalties` of a player. Provide an interpretation of
    the results.

8.  Could it be concluded that having more penalties increases the skill
    and success of a player in the form of HPI?

## References

[Kaggle Original
Dataset](https://www.kaggle.com/datasets/nemanjagojkovic/handball-bundesliga-stats-202223){target="_blank"}

[Olympic Handball
Rules](https://olympics.com/en/news/handball-game-rules-regulations-how-to-play){target="_blank"}

[Handball
Positions](https://www.theukrules.co.uk/rules/sport/handball/player-positions/#google_vignette){target="_blank"}

[Handball Performance Index (HPI)](https://www.liquimoly-hbl.de/en/s/handball-performance-index/2021-22/handball-performance-index--data-based--transparent--fair/){target="_blank"}
