---
title: "Raisin River Race Results 2015-2025"
author: "Phoebe Jones" 
date: "June 18, 2025" 

categories:
  - Linear Regression
  - Outliers 
---

## Motivation

Downriver paddling is a difficult and competitive sport. The Raisin River Race is one of the longest races in Eastern Ontario, spanning almost 19 miles on the Raisin River, from St. Andrews West to Williamstown. Paddlers compete against each other to achieve the fastest time in their class.

### Understanding Downriver Racing

Downriver racing is a sport where competitors take their watercraft (usually a canoe, kayak, or stand-up paddle board) down a race course in competition with other paddlers, sometimes navigating rapids, in an attempt to get the fastest time either overall or in their class (classes are split up by boat and paddler type). Times are tracked by race officials on shore.

#### Classes

The number of classes and how they are separated is variable depending on the race. For canoes, the Raisin River Race distinguishes classes first by canoe type: pro, rec, and medium. Different boat types have their advantages and disadvantages, but pro boats are typically faster and used by more experienced paddlers, while rec boats are slower and more commonly available. Class is also determined by how many paddlers are in the boat. For example, `oc2prowomen` refers to a pro canoe being paddled by 2 women and `oc1rec` refers to a recreational canoe being paddled by 1 person (the Raisin results are not separated by gender for solo canoes). 
Kayaks are split up by paddlers and their gender and by length: long (12 ft and over) or short (under 12 ft). For example, `k1student` refers to a kayak being paddled by a (1) student (any gender, this is not a popular enough class to be split by gender) and `k1longwomen` refers to a long kayak being paddled by a (1) woman. Long kayaks are typically faster, but less stable. 
Stand-up paddleboards are all in one class at the Raisin.

### Raisin River

The normal Raisin River course is about 18.6 miles (30 km). It contains some rapids of moderate difficulty and an optional portage (on land detour) around the Martintown Dam, which is a significantly more difficult drop than any other obstacles on the course. At very high water levels (the data set shows this in 2017), the race start is moved about 4 miles downriver, with the finish staying where is, making the race shorter.

## Data

The `raisin_river_full.csv` data set includes data from the Paddlestats database and the Raisin River Race website about the Raisin River Race from the years 2015-2025 (excluding 2020 and 2021 as no race was held due to the COVID-19 pandemic). It has 3222 observations and 19 variables. Each row (observation) represents a specific paddler that competed in the race in a given year. This means that boats with more than one paddler have more than one row in the data set, but have the same bib number and time.

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable    | Description                                          |
|-------------|------------------------------------------------------|
| displayName | Name of the racer                                    |
| bib         | Bib number                                           |
| year        | Year raced                                           |
| boatType    | Type of boat raced (canoe, kayak, SUP)               |
| classID     | Class (oc1, oc2, etc)                                |
| place       | Where the boat placed in their class's results       |
| time        | The time to complete the race (in sec)               |
| overall     | Overall rank (out of all boats all years)            |
| byBoat      | Rank out of all boats of the same type               |
| byClass     | Rank out of all boats in class (all years)           |
| byYrClass   | Rank out of the boats in their class in their year   |
| byYrOver    | Rank out of all the boats that year (all classes)    |
| byYrBoat    | Rank out of all boats of the same type that year     |
| courseID    | raisin - for normal course, raisin2017 - for shorter |
| status      | Finishing status (DNF, DNS, DQ, etc.)                | 
| flow        | Flow rate of the river that year (ft cubed/sec)      |

</details>

Download [raisin_river_full.csv](../data/raisin_river_full.csv){target="_blank"}

## Questions

1.  What class has the fastest times on average?
2.  Are there any unusual times (either fast or slow)?
3.  Does flow rate have an impact on time?

## References

[Paddlestats Website: Raisin River Race History](https://paddlestats.net/racehistory/RAISIN)

[Raisin River Race Website](https://rrca.on.ca/page.php?id=13)
