---
title: "rowing_submission_data_prep"
format: html
---

# Read in libraries

```{r}
library(tidyverse)
library(readr)
```

# Read in initial data set

Find the dataset on [this link](https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results?resource=download) and download it. 

```{r}
athletes_df <- read_csv("medals.csv")
```

# Set up rowing_df

```{r}
rowing_df <- athletes_df |> filter(Sport == "Rowing")
```

# Set up medals

```{r}
country_event <- rowing_df |> group_by(Event, NOC) |> summarise()
```

```{r}
write_excel_csv(country_event, "country_event.csv")
```

```{r}
events <- rowing_df |> group_by(Event) |> summarise()
```

```{r}
write_excel_csv(events, "events.csv")
```

```{r}
# `Number of Athletes` was edited manually in an excel file and then read back in a csv file
events_athletes <- read_csv("events_athletes.csv")
```

```{r}
events_noc_athletes <- left_join(country_event, events_athletes, by = "Event")
```

```{r}
rowingsum <- rowing_df |> mutate(n_medal= case_when(Medal == "Gold" ~ 1, Medal == "Silver" ~ 1, Medal == "Bronze" ~ 1, is.na(Medal) ~ 0)) |> mutate(n_point= case_when(Medal == "Gold" ~ 3, Medal == "Silver" ~ 2, Medal == "Bronze" ~ 1, is.na(Medal) ~ 0)) |> group_by(NOC) |> summarise(total_medals = sum(n_medal), total_points = sum(n_point))
```

```{r}
complete <- left_join(events_noc_athletes, rowingsum)
```

# Finalized medals

```{r}
medals <- complete |> mutate(total_medals = total_medals/`Number of Athletes`, total_points = total_points/`Number of Athletes`)
```

```{r}
write_excel_csv(medals, "medals.csv")
```
