---
title: Soccer Heights
author: Roderick Mpofu, Robin Lock
date: August 03, 2023
description: Heights for a sample of 100 soccer players by position 
categories:
  - ANOVA for means
  - Pairwise comparisons
---

## Motivation

A researcher wants to investigate whether there are differences among the mean height for different positions (Goalkeeper, Defender, Midfield, Attack, or Missing) of soccer players. Goalkeepers are typically thought to be taller than other positions to make up in wingspan to cover the goal better. The dataset contains information on each player including their name, position, preferred foot, and height. For this analysis, only the position and height of the player will be used. A sample of 20 players was taken from each position for this analysis.

## Data

Each row of data gives gives information for one of 100 soccer players in the sample with 20 players at each of five positions for a total sample size of 100.

| Variable       | Description               |
|----------------|---------------------------|
| `name`         | Name of the player        |
| `position`     | Player's current position |
| `foot`         | Player's preferred foot   |
| `height_in_cm` | Player's height (in cm)   |

[soccer_heights_sample.csv](../data/soccer_heights_sample.csv)

## Questions

1.  What are the mean heights for each position?

2.  Test to see if there is evidence of a discernible difference in mean height among the five positions.

3.  Which pairs of positions appear to have a discernible difference in mean height?

## References

The data was subsetted from the [data.world website](https://data.world/dcereijo/player-scores)
