---
title: Lacrosse PLL vs. NLL
author: AJ Dykstra, Jack Cowan, and Ivan Ramler
date: June 22, 2023
description: The data set looks at both lacrosse leagues, their respective teams, and their shot and goal amounts. 
categories:
  - Difference in means hypothesis tests
  - Difference in means confidence intervals
---

## Motivation

This data set examines the goals and shots in two prominent lacrosse leagues: the [Premier Lacrosse League](https://premierlacrosseleague.com/) (PLL) and the [National Lacrosse League](https://www.nll.com/) (NLL).

The PLL and NLL are highly regarded professional lacrosse leagues that feature top-tier athletes from around the world. The PLL is played in an indoor, smaller field while the NLL plays on an outdoor field with traditional dimensions. This data set allows for an analysis of goal-scoring within these leagues.

## Data

The data set has 162 rows with 9 columns. Each row represents a single lacrosse match either in the Premier Lacrosse League or the National Lacrosse League for the 2021 - 2022 season. NLL seasons typically run from December to May while PLL seasons typically run from June to September.

| Variable       | Description                                                    |
|------------------|------------------------------------------------------|
| League         | The Premier Lacrosse league and the National Lacrosse League   |
| Away_team      | The traveling team                                             |
| Home_team      | The hosting team                                               |
| Away_shots     | How many shots the `Away_team` had on net                      |
| Home_shots     | How many shots the `Home_team` had on net                      |
| Away_goals     | How many goals the `Away_team` had on net                      |
| Home_goals     | How many goals the `Home_team` had on net                      |
| goals_per_game | The total amount of goals scored each game                     |
| goals_per_48   | The average amount of goals for the first 48 minutes of a game |

: [lacrosse_pll_nll_2021-2022.csv](../data/lacrosse_pll_nll_2021-2022.csv)

## Questions

1.  Do these data provide evidence that, on average, goals scored in the PLL and NLL differ? Include all details of the appropriate hypothesis test.

2.  Construct and interpret a 95% confidence interval in average goals for NLL and PLL lacrosse games *per 48 minutes*.

## References

Premier Lacrosse League stats. Premier Lacrosse League Stats. (n.d.). <https://stats.premierlacrosseleague.com/>

Player stats. NLL. (2023, January 26). <https://www.nll.com/stats/all-player-stats/>
