---
title: "United Rugby Championships Player Profiles: 2024-25"
author: "Phoebe Jones" 
date: "June 26, 2025" 

categories:
  - Indicator variables 
  - Categorical variables
---

## Motivation

Unlike other sports, which often have a “look”, rugby is unique in that it is intended to be accessible to players of various shapes and sizes. Different positions have distinct expectations and therefore are best suited to people with distinct physiques. This makes the height and weight data interesting to explore, especially with regard to position.

### Understanding Rugby

Rugby is a sport that is primarily popular in Europe. Union rugby (the type this data is from) is played by 15 players on the pitch from each team. The pitch is roughly the size of an American Football field and has goalposts (similar to in football) on either side of the field. These goalposts lie on the “try line”. The goal of the teams is to get the ball past their respective try line, as doing so will score them 7 points. Points can also be earned by kicking the ball through the posts during the match.

#### Positions

This data splits the players up into 9 positions: prop, hooker, lock, back row, scrum-half, fly-half, centre, winger, fullback. On the field at one time there are 2 props, 1 hooker, 2 locks, 3 members of the back row, 2 wingers, 2 centres, 1 scrum-half, 1 fly-half, and 1 fullback. The props, locks, hooker, and back row are considered the forwards (generally attackers) and the other positions are the backs (generally defensive players).
The position defined as back row is actually 2 different positions: 2 flankers and a number 8.

### United Rugby Championship

The United Rugby Championship (URC) is a global league of 16 club teams from around the world. The championship is tournament style and split into 18 matches with knock-out stages leading to the final.

## Data

The `rugby_player_profiles_2024-25.csv` data set includes data from all.rugby about the make-up of each of the teams in the United Rugby Championships in 2024-2025. There are 723 players with 7 variables recorded for each.

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable    | Description                                  |
|-------------|----------------------------------------------|
| Name        | Player name (First LAST)                     |
| Position    | Player position (Scrum-Half, Winger, etc.)   |      
| Age         | Player age                                   |
| Birthdate   | Player birthdate (dd/mm/yyyy)                |
| Height      | Player height (meters)                       |
| Weight      | Player weight (kg)                           |
| Team        | Player team in the URC                       | 

</details>

Download [rugby_player_profiles_2024-25.csv](../data/rugby_player_profiles_2024-25.csv)

## Questions

1. Is there a relationship between height/weight and position?
2. Are some teams younger/older than average?
3. Are some positions held by older/younger players?

## References

[All Rugby URC Table](https://all.rugby/tournament/urc/table){target="_blank"}
